version: '3.3'

services:
  postgres:
    image: postgres:13
    environment: 
      - POSTGRES_DB=my_store
      - POSTGRES_USER=node      
      - POSTGRES_PASSWORD=store123
    ports:
      - 5434:5432
    volumes:
      - "postgres_data":/var/lib/postgresql/data
  
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/server/node_server
      - ./package.json:/server/package.json
      - ./package-lock.json:/server/package-lock.json
      - notused:/server/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DB_USER=node
      - DB_PASSWORD=store123
      - DB_HOST=localhost
      - DB_NAME=my_store
      - DB_PORT=5434

volumes:
  postgres_data: {}
  notused: {}

  #pgadmin:
  #  image: dpage/pgadmin4
  #  environment: 
  #   - PGADMIN_DEFAULT_EMAIL=andrixalexander15@gmail.com
  #    - PGADMIN_DEFAULT_PASSWORD=node_pgadmin 
  #  ports:
  #    - 5050:80
