version: '3.3'

services:
  postgres:
    image: postgres:13
    environment: 
      - POSTGRES_DB=my_store
      - POSTGRES_USER=node      
      - POSTGRES_PASSWORD=store123
    ports:
      - 5434:5432
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      target: DEV
      context: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/server/node_server
      - ./package.json:/server/package.json
      - ./package-lock.json:/server/package-lock.json
      - notused:/server/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DB_USER=node
      - DB_PASSWORD=store123
      - DB_HOST=postgres
      - DB_NAME=my_store
      - DB_PORT=5432
      - DATABASE_URL=postgres://node:store123@postgres:5432/my_store
      - API_KEY=store_123_priv
      - JWT_KEY=0ZH76fzhjMAkitKObrwJR4eaEyo2nSDT

volumes:
  postgres_data: {}
  notused: {}

  #pgadmin:
  #  image: dpage/pgadmin4
  #  environment: 
  #   - PGADMIN_DEFAULT_EMAIL=correo@gmail.com
  #    - PGADMIN_DEFAULT_PASSWORD=pg123
  #  ports:
  #    - 5050:80
